[build]
  command = "npm run build"
  functions = "functions"
  publish = "client/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://تحويل-كاش-api.herokuapp.com/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "16"